services:
  frontend:
    labels:
      - traefik.enable=true
      - traefik.http.services.frontend.loadbalancer.server.port=8080
      - traefik.http.routers.frontend-http.entrypoints=websecure
      - traefik.http.routers.frontend-http.tls=true
      - traefik.http.routers.frontend-http.rule=HostRegexp(`{any:.+}`)

  proxy:
    image: traefik:2.5
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --providers.file.filename=/dynamic/traefik_dynamic.yaml
    ports:
      - ${HTTP_PUBLISH_PORT:-80}:80
      - ${HTTPS_PUBLISH_PORT:-443}:443
    volumes:
      - cert-data:/certs
      - ../overrides/traefik_dynamic.yaml:/dynamic/traefik_dynamic.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  cert-data:
